services:
    app:
        container_name: fregate_app
        build:
            context: .
            dockerfile: client.dockerfile
        ports:
            - 8080:3000
        depends_on:
            - api
        environment:
            REACT_APP_INTRA_REDIRECT: ${INTRA_REDIRECT}
            REACT_APP_EMAILJS_SERVICE: ${EMAILJS_SERVICE}
            REACT_APP_EMAILJS_PUBLICKEY: ${EMAILJS_PUBLICKEY}
            REACT_APP_EMAILJS_TEMPLATE_CONTACT: ${EMAILJS_TEMPLATE_CONTACT}
            REACT_APP_EMAILJS_TEMPLATE_PAYMENT: ${EMAILJS_TEMPLATE_PAYMENT}
            REACT_APP_API_URL: ${API_URL}
            REACT_APP_PAYPAL_ID: ${PAYPAL_ID}
        networks:
            - front_network

    api:
        container_name: fregate_api
        build:
            context: .
            dockerfile: server.dockerfile
        ports:
            - 4242:4242
        networks:
            - back_network
            - front_network
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            REDIS_CRYPT_KEY: ${REDIS_CRYPT_KEY}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            INTRA_UID: ${INTRA_UID}
            INTRA_SECRET: ${INTRA_SECRET}
            APP_URL: ${APP_URL}
            CONTRIBUTION_TIME: ${CONTRIBUTION_TIME}
            CONTRIBUTION_PRICE: ${CONTRIBUTION_PRICE}
            AES: ${AES}
            PAYPAL_BASE: ${PAYPAL_BASE}
            PAYPAL_ID: ${PAYPAL_ID}
            PAYPAL_SECRET: ${PAYPAL_SECRET}
        restart: unless-stopped
        depends_on:
            - redis
            - postgres

    redis:
        container_name: fregate_redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        image: redis
        restart: always
        volumes:
            - bde:/redis/data
        networks:
            - back_network

    postgres:
        container_name: fregate_psql
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
          - bde:/postgres/data
        networks:
            - back_network

    phppgadmin:
        container_name: fregate_phppgadmin
        image: bitnami/phppgadmin
        restart: always
        environment:
                DATABASE_HOST: postgres
        depends_on:
            - postgres
        networks:
            - back_network
            - front_network
        ports:
            - 8443:8443
        volumes:
            - bde:/phppgadmin/data
volumes:
    bde:
        driver: local
networks:
    back_network:
        driver: bridge
    front_network:
        driver: bridge
