version: '3.8'

services:
    app:
        container_name: fregate_app
        build:
            context: .
            dockerfile: client.dockerfile
        volumes:
            - ./client:/app
        ports:
            # - 8080:3000
            - 3000:3000
        depends_on:
            - api
        networks:
            - front_network

    api:
        container_name: fregate_api
        build:
            context: .
            # target: production
            dockerfile: server.dockerfile
        ports:
            - 4242:4242
        networks:
            - back_network
            - front_network
        volumes:
            - ./server:/usr/src/app
        restart: unless-stopped
        depends_on:
            - redis
            - postgres

    redis:
        container_name: fregate_redis
        command: redis-server --requirepass "xeno1et2"
        image: redis
        volumes:
            - redis:/data
        networks:
            - back_network

    postgres:
        container_name: fregate_psql
        image: postgres
        restart: always
        environment:
                POSTGRES_DB: ${POSTGRES_DB}
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
          - bde:/var/lib/postgresql/data
        networks:
            - back_network
volumes:
    redis:
        driver: local
    bde:
networks:
    back_network:
        driver: bridge
    front_network:
        driver: bridge
