
Skip to content
Pull requests
Issues
Marketplace
Explore
@sur4c1
Link-Wolf /
bde
Private

Code
Issues
Pull requests
Actions
Projects
Wiki
Security

    Insights

bde/docker-compose.yml
@sur4c1
sur4c1 adding not so useless volume
Latest commit 8b50f20 3 days ago
History
2 contributors
@sur4c1
@Link-Wolf
76 lines (72 sloc) 1.71 KB
services:
    app:
        container_name: fregate_app
        build:
            context: .
            dockerfile: client.dockerfile
        ports:
            - 8080:3000
        depends_on:
            - api
        networks:
            - front_network

    api:
        container_name: fregate_api
        build:
            context: .
            dockerfile: server.dockerfile
        ports:
            - 4242:4242
        networks:
            - back_network
            - front_network
        restart: unless-stopped
        depends_on:
            - redis
            - postgres

    redis:
        container_name: fregate_redis
        command: redis-server --requirepass "xeno1et2"
        image: redis
        restart: always
        volumes:
            - bde:/redis/data
        networks:
            - back_network

    postgres:
        container_name: fregate_psql
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
                POSTGRES_DB: ${POSTGRES_DB}
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
          - bde:/postgres/data
        networks:
            - back_network

    phppgadmin:
        container_name: fregate_phppgadmin
        image: bitnami/phppgadmin
        restart: always
        environment:
                DATABASE_HOST: postgres
        depends_on:
            - postgres
        networks:
            - back_network
            - front_network
        ports:
            - 8443:8443
        volumes:
            - bde:/phppgadmin/data
volumes:
    bde:
        driver: local
networks:
    back_network:
        driver: bridge
    front_network:
        driver: bridge
